### ISSUE TITLE
Error on "registerMessageListener :: listener"

### ISSUE THREAD

**Issue by mebencomo** [guikeller/cordova-wearos-plugin#3]
Hi! I'm working with your plugin in my project and it gives me this error. What could be happening?

Thanks!

```
2021-02-15 11:04:48.307 15693-15778/? I/CordovaWearOsPlugin: constructor
2021-02-15 11:04:48.307 15693-15778/? I/CordovaWearOsPlugin: initialize
2021-02-15 11:04:48.307 15693-15778/? I/CordovaWearOsPlugin: execute
2021-02-15 11:04:48.308 15693-15778/? I/CordovaWearOsPlugin: init
2021-02-15 11:04:50.311 15693-15778/? I/CordovaWearOsPlugin: execute
2021-02-15 11:04:50.312 15693-15778/? I/CordovaWearOsPlugin: registerMessageListener :: listener: org.apache.cordova.CallbackContext@777fdca
2021-02-15 11:04:50.312 15693-15778/? I/CordovaWearOsPlugin: createWearOsMessageListener
2021-02-15 11:04:50.312 15693-15778/? I/CordovaWearOsPlugin: registerMessageListener
2021-02-15 11:04:50.352 15693-15778/? W/System.err: at com.google.android.gms.wearable.DataClient.(Unknown Source:3)
2021-02-15 11:04:50.353 15693-15778/? W/System.err: at com.google.android.gms.wearable.internal.zzcj.(Unknown Source:4)
2021-02-15 11:04:50.353 15693-15778/? W/System.err: at com.google.android.gms.wearable.Wearable.getDataClient(Unknown Source:5)
2021-02-15 11:04:50.353 15693-15778/? W/System.err: at com.github.guikeller.cordova.wearos.CordovaWearOsPlugin.registerWearableMessageListener(CordovaWearOsPlugin.java:129)
2021-02-15 11:04:50.353 15693-15778/? W/System.err: at com.github.guikeller.cordova.wearos.CordovaWearOsPlugin.registerMessageListener(CordovaWearOsPlugin.java:89)
2021-02-15 11:04:50.353 15693-15778/? W/System.err: at com.github.guikeller.cordova.wearos.CordovaWearOsPlugin.execute(CordovaWearOsPlugin.java:60)
```

**Comment by guy-keller** [comment]
> 2021-02-15 11:04:50.353 15693-15778/? W/System.err: at com.google.android.gms.wearable.Wearable.getDataClient(Unknown Source:5)
2021-02-15 11:04:50.353 15693-15778/? W/System.err: at com.github.guikeller.cordova.wearos.CordovaWearOsPlugin.registerWearableMessageListener(**CordovaWearOsPlugin.java:129**)
2021-02-15 11:04:50.353 15693-15778/? W/System.err: at com.github.guikeller.cordova.wearos.CordovaWearOsPlugin.registerMessageListener(CordovaWearOsPlugin.java:89)

Which is:
https://github.com/guikeller/cordova-wearos-plugin-source/blob/master/app/src/main/java/com/github/guikeller/cordova/wearos/CordovaWearOsPlugin.java#L129

```java
// L129
Wearable.getDataClient(context).addListener(new DataClient.OnDataChangedListener() {
   ...
}
```

Are you importing the following libs?
```
    implementation 'com.google.android.gms:play-services-base:+'
    implementation 'com.google.android.gms:play-services-wearable:+'
```
Source: https://stackoverflow.com/questions/58202877/error-while-accessing-android-wear-data-layer

**Comment by mebencomo** [comment]
Hi!.. Thanks for the answer.

Yes I'm importing those libs. Here is my cordova app build.gradle:

`apply plugin: 'com.android.application'

buildscript {
    repositories {
        mavenCentral()
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.3.0'
		
		
    }
}

// Allow plugins to declare Maven dependencies via build-extras.gradle.
allprojects {
    repositories {
        mavenCentral()
        jcenter()
    }
}

dependencies {
	implementation 'com.google.android.gms:play-services-base:+'
    implementation 'com.google.android.gms:play-services-wearable:+'
}

task wrapper(type: Wrapper) {
    gradleVersion = '4.10.3'
}

// Configuration properties. Set these via environment variables, build-extras.gradle, or gradle.properties.
// Refer to: http://www.gradle.org/docs/current/userguide/tutorial_this_and_that.html
ext {
    apply from: '../CordovaLib/cordova.gradle'

    // The value for android.compileSdkVersion.
    if (!project.hasProperty('cdvCompileSdkVersion')) {
        cdvCompileSdkVersion = null;
    }
    // The value for android.buildToolsVersion.
    if (!project.hasProperty('cdvBuildToolsVersion')) {
        cdvBuildToolsVersion = null;
    }
    // Sets the versionCode to the given value.
    if (!project.hasProperty('cdvVersionCode')) {
        cdvVersionCode = null
    }
    // Sets the minSdkVersion to the given value.
    if (!project.hasProperty('cdvMinSdkVersion')) {
        cdvMinSdkVersion = null
    }
    // Sets the maxSdkVersion to the given value.
    if (!project.hasProperty('cdvMaxSdkVersion')) {
        cdvMaxSdkVersion = null
    }
    // The value for android.targetSdkVersion.
    if (!project.hasProperty('cdvTargetSdkVersion')) {
        cdvTargetSdkVersion = null;
    }
    // Whether to build architecture-specific APKs.
    if (!project.hasProperty('cdvBuildMultipleApks')) {
        cdvBuildMultipleApks = null
    }
    // Whether to append a 0 "abi digit" to versionCode when only a single APK is build
    if (!project.hasProperty('cdvVersionCodeForceAbiDigit')) {
        cdvVersionCodeForceAbiDigit = null
    }
    // .properties files to use for release signing.
    if (!project.hasProperty('cdvReleaseSigningPropertiesFile')) {
        cdvReleaseSigningPropertiesFile = null
    }
    // .properties files to use for debug signing.
    if (!project.hasProperty('cdvDebugSigningPropertiesFile')) {
        cdvDebugSigningPropertiesFile = null
    }
    // Set by build.js script.
    if (!project.hasProperty('cdvBuildArch')) {
        cdvBuildArch = null
    }

    // Plugin gradle extensions can append to this to have code run at the end.
    cdvPluginPostBuildExtras = []
}

// PLUGIN GRADLE EXTENSIONS START
apply from: "../cordova-android-play-services-gradle-release/hellocordova-cordova-android-play-services-gradle-release.gradle"
apply from: "../cordova-wearos-plugin/hellocordova-cordova-wearos-plugin.gradle"
// PLUGIN GRADLE EXTENSIONS END

def hasBuildExtras1 = file('build-extras.gradle').exists()
if (hasBuildExtras1) {
    apply from: 'build-extras.gradle'
}

def hasBuildExtras2 = file('../build-extras.gradle').exists()
if (hasBuildExtras2) {
    apply from: '../build-extras.gradle'
}

// Set property defaults after extension .gradle files.
ext.cdvCompileSdkVersion = cdvCompileSdkVersion == null ? (
    defaultCompileSdkVersion == null 
        ? privateHelpers.getProjectTarget()
        : defaultCompileSdkVersion 
) : Integer.parseInt('' + cdvCompileSdkVersion);

if (ext.cdvBuildToolsVersion == null) {
    ext.cdvBuildToolsVersion = privateHelpers.findLatestInstalledBuildTools()
    //ext.cdvBuildToolsVersion = project.ext.defaultBuildToolsVersion
}
if (ext.cdvDebugSigningPropertiesFile == null && file('../debug-signing.properties').exists()) {
    ext.cdvDebugSigningPropertiesFile = '../debug-signing.properties'
}
if (ext.cdvReleaseSigningPropertiesFile == null && file('../release-signing.properties').exists()) {
    ext.cdvReleaseSigningPropertiesFile = '../release-signing.properties'
}

// Cast to appropriate types.
ext.cdvBuildMultipleApks = cdvBuildMultipleApks == null ? false : cdvBuildMultipleApks.toBoolean();
ext.cdvVersionCodeForceAbiDigit = cdvVersionCodeForceAbiDigit == null ? false : cdvVersionCodeForceAbiDigit.toBoolean();

// minSdkVersion, maxSdkVersion and targetSdkVersion
ext.cdvMinSdkVersion = cdvMinSdkVersion == null ? defaultMinSdkVersion : Integer.parseInt('' + cdvMinSdkVersion)
if (cdvMaxSdkVersion != null) {
    ext.cdvMaxSdkVersion = Integer.parseInt('' + cdvMaxSdkVersion)
}
ext.cdvTargetSdkVersion = cdvTargetSdkVersion == null ? defaultTargetSdkVersion  : Integer.parseInt('' + cdvTargetSdkVersion)

ext.cdvVersionCode = cdvVersionCode == null ? null : Integer.parseInt('' + cdvVersionCode)

def computeBuildTargetName(debugBuild) {
    def ret = 'assemble'
    if (cdvBuildMultipleApks && cdvBuildArch) {
        def arch = cdvBuildArch == 'arm' ? 'armv7' : cdvBuildArch
        ret += '' + arch.toUpperCase().charAt(0) + arch.substring(1);
    }
    return ret + (debugBuild ? 'Debug' : 'Release')
}

// Make cdvBuild a task that depends on the debug/arch-sepecific task.
task cdvBuildDebug
cdvBuildDebug.dependsOn {
    return computeBuildTargetName(true)
}

task cdvBuildRelease
cdvBuildRelease.dependsOn {
    return computeBuildTargetName(false)
}

task cdvPrintProps {
    doLast {
        println('cdvCompileSdkVersion=' + cdvCompileSdkVersion)
        println('cdvBuildToolsVersion=' + cdvBuildToolsVersion)
        println('cdvVersionCode=' + cdvVersionCode)
        println('cdvVersionCodeForceAbiDigit=' + cdvVersionCodeForceAbiDigit)
        println('cdvMinSdkVersion=' + cdvMinSdkVersion)
        println('cdvMaxSdkVersion=' + cdvMaxSdkVersion)
        println('cdvTargetSdkVersion=' + cdvTargetSdkVersion)
        println('cdvBuildMultipleApks=' + cdvBuildMultipleApks)
        println('cdvReleaseSigningPropertiesFile=' + cdvReleaseSigningPropertiesFile)
        println('cdvDebugSigningPropertiesFile=' + cdvDebugSigningPropertiesFile)
        println('cdvBuildArch=' + cdvBuildArch)
        println('computedVersionCode=' + android.defaultConfig.versionCode)
        android.productFlavors.each { flavor ->
            println('computed' + flavor.name.capitalize() + 'VersionCode=' + flavor.versionCode)
        }
    }
}

android {
    defaultConfig {
        versionCode cdvVersionCode ?: new BigInteger("" + privateHelpers.extractIntFromManifest("versionCode"))
        applicationId privateHelpers.extractStringFromManifest("package")

        if (cdvMinSdkVersion != null) {
            minSdkVersion cdvMinSdkVersion
        }

        if (cdvMaxSdkVersion != null) {
            maxSdkVersion cdvMaxSdkVersion
        }

        if(cdvTargetSdkVersion != null) {
            targetSdkVersion cdvTargetSdkVersion
        }
    }

    lintOptions {
      abortOnError false;
    }

    compileSdkVersion cdvCompileSdkVersion
    buildToolsVersion cdvBuildToolsVersion

    // This code exists for Crosswalk and other Native APIs.
    // By default, we multiply the existing version code in the
    // Android Manifest by 10 and add a number for each architecture.
    // If you are not using Crosswalk or SQLite, you can
    // ignore this chunk of code, and your version codes will be respected.

    if (Boolean.valueOf(cdvBuildMultipleApks)) {
        flavorDimensions "default"

        productFlavors {
            armeabi {
                versionCode defaultConfig.versionCode*10 + 1
                ndk {
                    abiFilters = ["armeabi"]
                }
            }
            armv7 {
                versionCode defaultConfig.versionCode*10 + 2
                ndk {
                    abiFilters = ["armeabi-v7a"]
                }
            }
            arm64 {
                versionCode defaultConfig.versionCode*10 + 3
                ndk {
                    abiFilters = ["arm64-v8a"]
                }
            }
            x86 {
                versionCode defaultConfig.versionCode*10 + 4
                ndk {
                    abiFilters = ["x86"]
                }
            }
            x86_64 {
                versionCode defaultConfig.versionCode*10 + 5
                ndk {
                    abiFilters = ["x86_64"]
                }
            }
        }
    } else if (Boolean.valueOf(cdvVersionCodeForceAbiDigit)) {
        // This provides compatibility to the default logic for versionCode before cordova-android 5.2.0
        defaultConfig {
            versionCode defaultConfig.versionCode*10
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    if (cdvReleaseSigningPropertiesFile) {
        signingConfigs {
            release {
                // These must be set or Gradle will complain (even if they are overridden).
                keyAlias = ""
                keyPassword = "__unset" // And these must be set to non-empty in order to have the signing step added to the task graph.
                storeFile = null
                storePassword = "__unset"
            }
        }
        buildTypes {
            release {
                signingConfig signingConfigs.release
            }
        }
        addSigningProps(cdvReleaseSigningPropertiesFile, signingConfigs.release)
    }

    if (cdvDebugSigningPropertiesFile) {
        addSigningProps(cdvDebugSigningPropertiesFile, signingConfigs.debug)
    }
}

/*
 * WARNING: Cordova Lib and platform scripts do management inside of this code here,
 * if you are adding the dependencies manually, do so outside the comments, otherwise
 * the Cordova tools will overwrite them
 */


dependencies {
    implementation fileTree(dir: 'libs', include: '*.jar')
    // SUB-PROJECT DEPENDENCIES START
    implementation(project(path: ":CordovaLib"))
    implementation "com.google.android.gms:play-services-base:11+"
    implementation "com.google.android.gms:play-services-wearable:11+"
    // SUB-PROJECT DEPENDENCIES END
}

def promptForReleaseKeyPassword() {
    if (!cdvReleaseSigningPropertiesFile) {
        return;
    }
    if ('__unset'.equals(android.signingConfigs.release.storePassword)) {
        android.signingConfigs.release.storePassword = privateHelpers.promptForPassword('Enter key store password: ')
    }
    if ('__unset'.equals(android.signingConfigs.release.keyPassword)) {
        android.signingConfigs.release.keyPassword = privateHelpers.promptForPassword('Enter key password: ');
    }
}

gradle.taskGraph.whenReady { taskGraph ->
    taskGraph.getAllTasks().each() { task ->
      if(['validateReleaseSigning', 'validateSigningRelease', 'validateSigningArmv7Release', 'validateSigningX76Release'].contains(task.name)) {
         promptForReleaseKeyPassword()
      }
    }
}

def addSigningProps(propsFilePath, signingConfig) {
    def propsFile = file(propsFilePath)
    def props = new Properties()
    propsFile.withReader { reader ->
        props.load(reader)
    }

    def storeFile = new File(props.get('key.store') ?: privateHelpers.ensureValueExists(propsFilePath, props, 'storeFile'))
    if (!storeFile.isAbsolute()) {
        storeFile = RelativePath.parse(true, storeFile.toString()).getFile(propsFile.getParentFile())
    }
    if (!storeFile.exists()) {
        throw new FileNotFoundException('Keystore file does not exist: ' + storeFile.getAbsolutePath())
    }
    signingConfig.keyAlias = props.get('key.alias') ?: privateHelpers.ensureValueExists(propsFilePath, props, 'keyAlias')
    signingConfig.keyPassword = props.get('keyPassword', props.get('key.alias.password', signingConfig.keyPassword))
    signingConfig.storeFile = storeFile
    signingConfig.storePassword = props.get('storePassword', props.get('key.store.password', signingConfig.storePassword))
    def storeType = props.get('storeType', props.get('key.store.type', ''))
    if (!storeType) {
        def filename = storeFile.getName().toLowerCase();
        if (filename.endsWith('.p12') || filename.endsWith('.pfx')) {
            storeType = 'pkcs12'
        } else {
            storeType = signingConfig.storeType // "jks"
        }
    }
    signingConfig.storeType = storeType
}

for (def func : cdvPluginPostBuildExtras) {
    func()
}

// This can be defined within build-extras.gradle as:
//     ext.postBuildExtras = { ... code here ... }
if (hasProperty('postBuildExtras')) {
    postBuildExtras()
}`

**Comment by mebencomo** [comment]
Hi! Thanks for the answer. Yes, I'm importing those libs. Here is my cordova app build gradle:

apply plugin: 'com.android.application'

buildscript {
    repositories {
        mavenCentral()
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.3.0'
		
		
    }
}

// Allow plugins to declare Maven dependencies via build-extras.gradle.
allprojects {
    repositories {
        mavenCentral()
        jcenter()
    }
}

dependencies {
	implementation 'com.google.android.gms:play-services-base:+'
    implementation 'com.google.android.gms:play-services-wearable:+'
}

task wrapper(type: Wrapper) {
    gradleVersion = '4.10.3'
}

**Comment by mebencomo** [comment]
Hi! Thanks for the answer. Yes, I'm importing those libs. Here is my cordova app build gradle:
```
/*
 * WARNING: Cordova Lib and platform scripts do management inside of this code here,
 * if you are adding the dependencies manually, do so outside the comments, otherwise
 * the Cordova tools will overwrite them
 */


dependencies {
    implementation fileTree(dir: 'libs', include: '*.jar')
    // SUB-PROJECT DEPENDENCIES START
    implementation(project(path: ":CordovaLib"))
    implementation "com.google.android.gms:play-services-base:+"
    implementation "com.google.android.gms:play-services-wearable:+"
    // SUB-PROJECT DEPENDENCIES END
}

```

**Comment by mebencomo** [comment]
I also use **implementation 'com.google.android.gms:play-services-base:17.2.1'**. But i got the same error

**Comment by guy-keller** [comment]
Did you also install the other plugins required?

```
cordova-plugin-androidx
cordova-plugin-androidx-adapter
cordova-android-play-services-gradle-release
```

**Comment by mebencomo** [comment]
Yes. I've following all the steps that you indicates.

**Comment by mebencomo** [comment]
In build.gradle:

// PLUGIN GRADLE EXTENSIONS START
apply from: "../cordova-android-play-services-gradle-release/hellocordova-cordova-android-play-services-gradle-release.gradle"

**Comment by mebencomo** [comment]
I have an addionatl question: to test all project i'm using my phone (cordova app) and wear androind studio emulator, is that correct?

**Comment by guy-keller** [comment]
Hi @mebencomo 

Q) To test the project I'm using my phone (Cordova app) and an emulated WearOS (Android Studio), is that okay?
A) To be honest, I have never tested against the watch emulator / always used real devices.
Would you be able to test against a real WearOS device?

Also, as the error message says the following:
>
2021-02-15 11:04:50.312 15693-15778/? I/CordovaWearOsPlugin: registerMessageListener
2021-02-15 11:04:50.352 15693-15778/? W/System.err: at com.google.android.gms.wearable.**DataClient**.(Unknown Source:3)
2021-02-15 11:04:50.353 15693-15778/? W/System.err: at com.google.android.gms.wearable.internal.zzcj.(Unknown Source:4)
2021-02-15 11:04:50.353 15693-15778/? W/System.err: at com.google.android.gms.wearable.Wearable.**getDataClient**(Unknown Source:5)

I wonder if there is any connection to this ( ? ) :
https://developer.android.com/training/wearables/data-layer/migrate-to-googleapi

Do you have the "*Wear OS*" app installed on your mobile phone as well?
_Thinking out loud_: I do not think that will work against the emulator (real mobile X emulated watch)

**Comment by guy-keller** [comment]
Hi @mebencomo 

Any progress? :)

**Comment by mebencomo** [comment]
Hi! I have WearOS app in my phone. I've beben using ADB command to connect my phone and the emulator.

They emulator see my phone like a node to deespach the Message. But the phone won't recive it.

**Comment by mebencomo** [comment]
Hi! I have WearOS app in my phone. I've been using ADB command to connect my phone and the emulator.

They emulator see my phone like a node to deespach the Message. But the phone won't recive it.

The phone won't connect with the emulator.

**Comment by guy-keller** [comment]
Hi @mebencomo 

I believe that is something to do with the emulator in the mix.

See this tutorial on how to do the emulator "**Wearable Configuration**" to talk to your phone.
https://heartbeat.fritz.ai/connect-android-devices-with-an-android-wear-emulator-338c8e50e8a4

As you can see it is not quite like a walk in the park with the emulator in the mix.
In addition to that keep an eye on the issue: #4 

Cheers, Gui

**Comment by mebencomo** [comment]
Hi!! 

It's working now! I was working with an old version for the emulator.

Thank you so much for your support!!

**Comment by guy-keller** [comment]
Hi @mebencomo 

No worries, I am glad to hear that you managed to send/receive messages between your Cordova and WearOS app.
Is there anything in the docs that needs better explaining? 

Good luck with your project, cheers!
